#!/usr/bin/env python
#
# -*- coding: CP1252 -*-
#
# generated by wxGlade 0.6.6 (standalone edition) on Thu Apr 04 23:06:43 2013
#

# This is an automatically generated file.
# Manual changes will be overwritten without warning!

import wx
import gettext
from guiEx import MainWindowEx
from BitcoinThread import BitcoinThread
from Queue import Queue

workQueue = Queue()

if __name__ == "__main__":
  gettext.install("advbtc")

  btc = BitcoinThread(workQueue)
  btc.setDaemon(True)
  btc.start()

  app = wx.App()
  frame_1 = MainWindowEx(workQueue)
  app.SetTopWindow(frame_1)
  frame_1.Show()
  app.MainLoop()
