# -*- coding: CP1252 -*-
#
# generated by wxGlade 0.6.6 (standalone edition) on Fri Apr 05 23:40:55 2013
#

import wx
# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
from CustomListControl import CustomListControl
# end wxGlade


class MyFrame(wx.Frame):
  def __init__(self, *args, **kwds):
    # begin wxGlade: MyFrame.__init__
    kwds["style"] = wx.DEFAULT_FRAME_STYLE
    wx.Frame.__init__(self, *args, **kwds)
    self.panel_1 = wx.Panel(self, wx.ID_ANY)
    self.label_1 = wx.StaticText(self.panel_1, wx.ID_ANY, _("Confirmed Balance:  "))
    self.cBalance = wx.StaticText(self.panel_1, wx.ID_ANY, _("loading"))
    self.label_3 = wx.StaticText(self.panel_1, wx.ID_ANY, _("Unconfirmed Balance:  "))
    self.ucBalance = wx.StaticText(self.panel_1, wx.ID_ANY, _("loading"))
    self.label_4 = wx.StaticText(self.panel_1, wx.ID_ANY, _("Show addresses with 0 balance:  "))
    self.showZero = wx.CheckBox(self.panel_1, wx.ID_ANY, "")
    self.label_5 = wx.StaticText(self.panel_1, wx.ID_ANY, _("Number of Addresses:  "))
    self.numAddrs = wx.StaticText(self.panel_1, wx.ID_ANY, _("?"))
    self.showAddr = wx.Button(self.panel_1, wx.ID_ANY, _("Show Addresses"))
    self.showTx = wx.Button(self.panel_1, wx.ID_ANY, _("Show Transactions"))
    self.addrlist = CustomListControl(self, wx.ID_ANY, style=wx.LC_REPORT | wx.SUNKEN_BORDER)
    self.txlist = CustomListControl(self, wx.ID_ANY, style=wx.LC_REPORT | wx.SUNKEN_BORDER)

    self.__set_properties()
    self.__do_layout()

    self.Bind(wx.EVT_CHECKBOX, self.showZeroToggle, self.showZero)
    self.Bind(wx.EVT_BUTTON, self.loadAddresses, self.showAddr)
    self.Bind(wx.EVT_BUTTON, self.loadTransactions, self.showTx)
    self.Bind(wx.EVT_LIST_ITEM_DESELECTED, self.disableTxButton, self.addrlist)
    self.Bind(wx.EVT_LIST_ITEM_SELECTED, self.enableTxButton, self.addrlist)
    # end wxGlade

  def __set_properties(self):
    # begin wxGlade: MyFrame.__set_properties
    self.SetTitle(_("advbtc"))
    self.SetSize((1066, 747))
    self.showTx.Enable(False)
    # end wxGlade

  def __do_layout(self):
    # begin wxGlade: MyFrame.__do_layout
    grid_sizer_1 = wx.GridSizer(2, 1, 0, 0)
    grid_sizer_2 = wx.GridSizer(1, 2, 0, 0)
    grid_sizer_3 = wx.GridSizer(7, 2, 0, 0)
    grid_sizer_3.Add(self.label_1, 0, wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL, 0)
    grid_sizer_3.Add(self.cBalance, 0, wx.ALIGN_CENTER_VERTICAL, 0)
    grid_sizer_3.Add(self.label_3, 0, wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL, 0)
    grid_sizer_3.Add(self.ucBalance, 0, wx.ALIGN_CENTER_VERTICAL, 0)
    grid_sizer_3.Add(self.label_4, 0, wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL, 0)
    grid_sizer_3.Add(self.showZero, 0, wx.ALIGN_CENTER_VERTICAL, 0)
    grid_sizer_3.Add(self.label_5, 0, wx.ALIGN_RIGHT | wx.ALIGN_CENTER_VERTICAL, 0)
    grid_sizer_3.Add(self.numAddrs, 0, wx.ALIGN_CENTER_VERTICAL, 0)
    grid_sizer_3.Add(self.showAddr, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
    grid_sizer_3.Add(self.showTx, 0, wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
    self.panel_1.SetSizer(grid_sizer_3)
    grid_sizer_2.Add(self.panel_1, 1, wx.EXPAND | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 20)
    grid_sizer_2.Add(self.addrlist, 1, wx.EXPAND, 0)
    grid_sizer_1.Add(grid_sizer_2, 1, wx.EXPAND, 0)
    grid_sizer_1.Add(self.txlist, 1, wx.EXPAND, 0)
    self.SetSizer(grid_sizer_1)
    self.Layout()
    # end wxGlade

  def showZeroToggle(self, event):  # wxGlade: MyFrame.<event_handler>
    print "Event handler 'showZeroToggle' not implemented!"
    event.Skip()

  def loadAddresses(self, event):  # wxGlade: MyFrame.<event_handler>
    print "Event handler 'loadAddresses' not implemented!"
    event.Skip()

  def loadTransactions(self, event):  # wxGlade: MyFrame.<event_handler>
    print "Event handler 'loadTransactions' not implemented!"
    event.Skip()

  def disableTxButton(self, event):  # wxGlade: MyFrame.<event_handler>
    print "Event handler 'disableTxButton' not implemented!"
    event.Skip()

  def enableTxButton(self, event):  # wxGlade: MyFrame.<event_handler>
    print "Event handler 'enableTxButton' not implemented!"
    event.Skip()

# end of class MyFrame
